import axios from 'axios'
import { createCsvSegmentUrl } from './urls'
import { getDefaultHeaders } from './utils'

export const createSegmentFromCsv = (data: any) => {
  const config = {
    headers: {
      ...getDefaultHeaders(),
      asset: 'userSegment',
    },
  }

  return axios.post(createCsvSegmentUrl, data, config)
  // console.log(`segment at api point ${JSON.stringify(data)}`)

  // const dummyResponse = {
  //   count: 1,
  //   segment: {
  //     id: 199,
  //     name: `Segment for bot: ${'botName'}`,
  //     description: `Autogenerated by admin panel for bot: ${'botName'}`,
  //     created_at: '2023-03-03T15:10:01.711001+05:30',
  //     updated_at: '2023-03-03T15:10:01.711001+05:30',
  //   },
  // }
  // return Promise.resolve(dummyResponse)
  //   .then((res: any) => {
  //     return res
  //   })
  //   .catch((err) => {})
}
